### ISSUE TITLE
Understanding the discrepancy between relay bandwidths in `shadow.config.yaml` and in `v3bw.init.consensus`

### ISSUE THREAD

**Issue by higher-order** [shadow/tornettools#111]
From my reading of the tornettools code, it seems like tornettools reads through a bunch of real historical consensuses among dirauths, gets the value of the `w Bandwidth=` line for each relay from each consensus, takes the median of that for each relay among all consensuses, and sets that as the `weight` of each relay in the relay staging file `relayinfo_staging_2023-04-01--2023-04-30.json`. It then normalizes the `weight` of relays in the staging file and writes that into `shadow.data.template/hosts/bwauthority/v3bw.init.consensus`.

It also reads through a bunch of relay descriptors and uses data from there for the `bandwidth_capacity`, `bandwidth_rate`, and `bandwidth_burst` of relays in the relay staging file. It also then sets the `bandwidth_down` and `bandwidth_up` of relays in `shadow.config.yaml` to the `bandwidth_capacity` in the staging file.

This means that the *actual* bandwidths of relays in the simulation are the *self-reported* bandwidths from relay descriptors in the real world, and the values in the v3bw are normalized from the bandwidths in the real historical consensuses, which are *measured* by the bandwidth scanner sbws.

I then ran an experiment, which has one simulation with the original config from `tornettools generate`, and another simulation where I read the `bandwidth_down` from the generated `shadow.config.yaml` (instead of from the relay descriptors), normalized them the same way tornettools did, and created a new `v3bw.init.consensus` based on that. I thought this would decrease the gap between relays' actual bandwidths in the simulation, and the v3bw in the simluation. However, the experiment showed that the performance dropped by a little, as a result.

I'd like to ask why is there such a gap between `shadow.config.yaml` and `v3bw.init.consensus`, as described above? And also why would my experiment show worse performance, after I tried to lessen the gap?

The experiment plot is attached.
[tornet.plot.pages.pdf](https://github.com/user-attachments/files/17386487/tornet.plot.pages.pdf)

**Comment by robgjansen** [comment]
The main thing you should realize is that the `w Bandwidth=` line in the consensus files is NOT a bandwidth value, despite the confusing name. It is a relay selection **weight** that may or may not be correlated with the actual raw network bandwidth capacity of the relay. Yes, there are some sbws measurements that go into the process of computing the relays' `w` consensus weights, but sbws does not do a very good job of discovering the relays' true bandwidth capacities. I don't think it was ever designed for that purpose. It is designed to compute relative performance across different relays, and it uses the relative performance to compute weights.

So, the bandwidth capacity of a relay is best measured with a speed test, but alas Tor never adopted that approach. So tornettools relies on the next best thing currently available, the bandwidth history, specifically, the maximum sustained throughout over a 10s period a relay has observed. This is a sort of metric for what the relay can handle. Of course if the relay is never pushed to it's limit, this number will not be correct. Also, the relay could lie about it. But it's the best we have until a more secure speedtest measurement system is deployed, which does not seem to be a priority for Tor atm.

If you want to learn more about the bandwidth numbers, I highly recommend you read this paper, or at least listen to my recording of my talk where I presented the main results.

On the Accuracy of Tor Bandwidth Estimation
https://www.robgjansen.com/publications/torbwest-pam2021.html

There are also several new approaches to actually measuring relay bandwidth capacities. In my biased opinion, the active measurement approach of FlashFlow is one of the best, which you can learn more about here:
https://www.robgjansen.com/publications/flashflow-icdcs2021.html

**Comment by higher-order** [comment]
Hi @robgjansen, thanks for sharing the information. I've watched the presentation as well. But I still can't connect the dots between the given facts and the question of why the "perfect" v3bw I designed couldn't improve the network's performance.

From what you said, I've understood that tornettools use relays' self-reported bandwidths from their relay descriptors as the ground truth of relay bandwidths in `shadow.config.yaml`. This is because the `w Bandwidth` values in the consensuses come from sbws, which measures relative performance rather than absolute performance. So there is not a better option.

But from what I see in the tornettools' code, it uses the `w Bandwidth` values from the consensuses to generate `v3bw.init.consensus`. This means that there is more or less of a gap between the bandwidths in `shadow.config.yaml` and the bandwidths in `v3bw.init.consensus`, since the former is from relay descriptors, while the latter is from consensuses. My "perfect" v3bw is generated by basically copying the bandwidths in `shadow.config.yaml`, and then applying the same renormalization as tornettools did (converting bandwidths to portions overall then dividing by the minimum). Wouldn't this "perfect" v3bw more accurately reflect the simulation ground truth in `shadow.config.yaml`, than the original one? Therefore I'm confused why the simulation shows it instead decreasing the performance a little, as shown in the PDF I attached at the top.

Note that I did rename the "perfect" v3bw to `v3bw.init.consensus` as well before simulating.

**Comment by robgjansen** [comment]
Hmm. Could it be that Tor internally does not actually send traffic perfectly across the relays, even if the weights are perfect? Perhaps the positional bandwidth weights are not optimized correctly after you set the "perfect" per-relay weights.

Tor does not treat each relay identically - it has different weight adjustments that it applies to each relay's weight depending on the relay position (entry, middle, exit) and the total bandwidth available across relay positions. So even if you apply the "perfect" _per-relay_ weight to each individual relay, your simulated Tor may apply non-optimal _positional_ weights to TRY to help balance overall load across entry, middle, and exit positions. If the positional weights are non-optimal for your specific set of relays after you manually adjusted the weights, then the positional weighting could lead to the slight drop in performance you notice.

There are many positional weights:
https://consensus-health.torproject.org/#bwweights

The code that applies these positional weights to each per-relay weight is not exactly simple:
https://gitlab.com/torproject/tor/-/blob/master/src/feature/nodelist/node_select.c#L604

FWIW, I've noticed many problems with Tor's load balancing over the years (which is why I worked on those papers trying to fix it). Based on the number of problems and complexity of Tor's load balancing, my intuition is that the problem you notice is some artifact of how Tor works and is not necessarily a problem with Shadow. Or, said a different way, we would need a lot more evidence that points to something specific about Shadow before we could blame Shadow for Tor's non-optimal load balancing. I'm not saying that there 100% is not a problem in Shadow, but right now we would have no idea where to look.

(We've also had other cases where more correct load balancing weights had the expected result - [Section 6B in the FlashFlow paper](https://www.robgjansen.com/publications/flashflow-icdcs2021.pdf).)

**Comment by higher-order** [comment]
@robgjansen Regarding positional weights: Wouldn't they be applied after the per-relay weights? That is, the dirauths measure and compute the per-relay weights, and publish them in the consensuses. The clients download the consensuses, and compute positional weights. I didn't dive into the code, but wouldn't clients compute better positional weights based on better per-relay weights?

I've read the FlashFlow paper before and got the main idea. I just skimmed it again as well. I didn't find much about positional weights in the paper. In fact, it seems to me that what I did is similar to FlashFlow. From the paper:
> Each BWAuth separately measures each relay during a period. The coordinator records the results as weights in a v3bw file, a format already used by DirAuths. Then standard Tor processes take over: the DirAuth reads the v3bw files produced by its BWAuth and votes with other DirAuths for consensus on relay weights every hour."

It seems like both FlashFlow and my experiment try to compute a better v3bw. After that, I assume all that needs to be done is to point `shadow.data/hosts/bwauthority/v3bw` to the computed v3bw. Unless there are other things besides pointing `v3bw` to the better file, I don't see much difference. Do you see any difference between the two?

Finally, could it be that my simulations were run in two different networks? I generated one network for the original (unmodified) simulation and generated another for simulating the perfect v3bw. Should I have only generated once instead, and make a copy of it to simulate both experiments?

**Comment by robgjansen** [comment]
> Regarding positional weights: Wouldn't they be applied after the per-relay weights? That is, the dirauths measure and compute the per-relay weights, and publish them in the consensuses. The clients download the consensuses, and compute positional weights.

Not exactly. The positional weights are computed by the dirauths and published in the consensus too. See the `directory-footer` part of any recent consensus as an example:

```
directory-footer
bandwidth-weights Wbd=287 Wbe=0 Wbg=3975 Wbm=10000 Wdb=10000 Web=10000 Wed=9426 Wee=10000 Weg=9426 Wem=10000 Wgb=10000 Wgd=287 Wgg=6025 Wgm=6025 Wmb=10000 Wmd=287 Wme=0 Wmg=3975 Wmm=10000
```

These are the global positional weights that get applied to each relay weight during client path selection. Recent consensus here: http://216.218.219.41/tor/status-vote/current/consensus

But yeah, those weights are usually computed after using a v3bw file as input. And those weights *should* automatically adjust as the relay weights change. But my point is that if your relay weights in your new network changed in a dramatic way to cause those positional weights to be VERY different from normal, then that could put your new network into a different state than the baseline network and could cause a big performance difference. But.... see below.

> Finally, could it be that my simulations were run in two different networks? I generated one network for the original (unmodified) simulation and generated another for simulating the perfect v3bw. Should I have only generated once instead, and make a copy of it to simulate both experiments?

Oh! Yes, this is absolutely a problem! Whenever you run `tornettools generate` you are making new random choices over which relays will be included in your network. Sometimes you can generate two very different networks. If you want a true apples-to-apples comparison, your suggestion is correct: you should generate one network and copy it to simulate a v3bw variant. And then, you should ALSO repeat that generate+copy procedure many times to gain confidence that some performance difference you saw in one generated network holds in all types of different generated networks.

Sorry to keep dumping papers on you, but we tried to document best practices in methodology here:
https://www.robgjansen.com/publications/neverenough-sec2021.html

If you are trying to produce scientifically defendable results, you should read that one too :)

**Comment by jtracey** [comment]
Rob is right, in this case, you need to not resample so that the measurements remain valid. A bit of clarification for this point though: the recommendations in the "Never Enough" paper/the experiments we did for it used independent samples each time, across the control variable (see "Simulation Configuration" in §6.2). In the general case, the difference between resampling and not resampling is a bit nuanced: the CIs you should produce if you *don't* resample represent the probable *effect* for if you made this change vs. if you didn't, while the CIs we made *with* resampling represent the probable *measurements* for if  you made this change vs. if you didn't. Because we only have access to one reality, those two aren't quite the same thing, and which you should be measuring depends on your goal (measuring for a likely impact, or measuring for an observable effect). IIRC, we mainly went for resampling because it makes the math sound (certain distributions are no longer independent otherwise, so our formulas for CI don't technically hold). Ideally, if your networks are large/numerous enough, the difference should hopefully be small, but that will depend on how significant any difference is. If you'd like, I can share a bit of experimentation I did after that paper (nothing published, just me playing around) using bootstrapping instead of analytical methods, which would allow you to generate CIs using whichever comparison you like, at the cost of wider bounds.

**Comment by higher-order** [comment]
@robgjansen @jtracey Thank you very much for sharing the information. I was able to generate a better "perfect" v3bw which beat the original network. While I was still using the previously described method, which generates a v3bw that aligns with relays' bandwidth capacities defined in `shadow.config.yaml`, I tried two simulations on the same copy of the generated network, as discussed earlier. However, the performance still decreased. Then my research group had a simple but important insight, which is that even if a relay has a high bandwidth capacity, they may experience a higher load during the simulation. For example, an exit relay may have twice as much bandwidth, but experience 10 times as much traffic. In that case it will be more overloaded and shouldn't be weighted higher in the v3bw.

So instead, I generated a network and made a copy of it, ran the first copy unmodified, and generated a v3bw for the second copy which weighs by relays' throughput observed during the first simulation. The throughput were parsed from `oniontrace.analysis.json.xz`. This improves the performance of the second simulation to be higher than the first. The plot is attached 
[tornet.plot.pages.pdf](https://github.com/user-attachments/files/18263835/tornet.plot.pages.pdf)


This also corresponds with an earlier point about how my method is very similar to what FlashFlow does and yet it can't improve the performance. The key difference is that FlashFlow generates v3bw using observed throughput, while my method used bandwidth capacity. So it seems like it's better to weigh the relays by observed throughput, and not bandwidth capacity.

Thanks again for the help on this matter. And yes I'd love to see the experimentation you did after the paper that you mentioned @jtracey

**Comment by jtracey** [comment]
@higher-order here's a commit that adds the gist of it: https://github.com/neverenough-sec2021/neverenough-sec2021.github.io/commit/d6450c772be8df498d5a4da04031c361886f34e3

It was just me playing with the idea, so the code isn't great and was never reviewed, but I was able to generate some decent plots with it, so it should help get the idea across, which is that we can plot the *ratio* of two values (e.g., throughput in experiment 2 to throughput in experiment 1) using [bootstrapping](https://en.wikipedia.org/wiki/Bootstrapping_(statistics)), so that instead of answering questions like "how do the distributions compare" (e.g., "the file took n seconds to download at each percentile for each respective configuration"), we can answer questions like "how did performance change" (e.g., "using this v3bw made things n times faster/slower at each percentile").

**Comment by higher-order** [comment]
@jtracey That seems very useful and what I have often wanted, thanks!
